export const LOGAR = 'LOGAR';
export const LOGOUT = 'LOGOUT';
export const ERROR_LOGAR = 'ERROR_LOGAR';
export const PEGAR_DADOS_USUARIO = 'PEGAR_DADOS_USUARIO';

export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';

//Categorias
export const LISTA_ESPECIALIDADE_CATEGORIAS = 'LISTA_ESPECIALIDADE_CATEGORIAS';
export const ESVAZIAR_CATEGORIAS = 'ESVAZIAR_CATEGORIAS';